### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by aswanthkrishna** [atomistic-machine-learning/schnetpack-gschnet#4]
Thank you for this awsome repo!. Are the pre-trained models from the previous repository compatible with the models defined here?

**Comment by NiklasGebauer** [comment]
Hi @aswanthkrishna,

glad you like our new code base! Unfortunately, the pre-trained models from the previous repos are not compatible since we had significant code changes.
Which models (i.e. properties for conditioning) are you interested in? I might add pre-trained models at a later point if there is demand for it. I cannot promise that this will happen soon, though, as training the models and testing/validating them + adding some instructions how to load and use them will take some extra time and I'm a little busy at the moment. So if you have the computational resources, training a model on your own would most likely be faster.

Best regards,
Niklas

**Comment by NiklasGebauer** [comment]
I will close this for now, feel free to re-open the issue if specific pre-trained models are needed.
